### ISSUE TITLE
What is point of tutorial overview page?

### ISSUE THREAD

**Issue by darklordabc** [ModDota/moddota.github.io#29]
It's just a copy of what is already on the lefthand navigation panel. I think it should just be removed. 
![image](https://user-images.githubusercontent.com/16277198/83717072-0ac09880-a675-11ea-93b8-3e3f9e2eadde.png)

**Comment by Perryvw** [comment]
The point is to have one list that gives a full overview of all tutorials. It will be moved to the top bar once a bug in docusaurus is fixed.
